<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');
$config['base_url']	= '';
//$config['static_url']	= 'http://static.51chance.com.cn/chinahr/chinahr_v2/';

/*
|--------------------------------------------------------------------------
| Index File
|--------------------------------------------------------------------------
|
| Typically this will be your index.php file, unless you've renamed it to
| something else. If you are using mod_rewrite to remove the page set this
| variable so that it is blank.
|
*/
$config['index_page'] = '';

/*
|--------------------------------------------------------------------------
| URI PROTOCOL
|--------------------------------------------------------------------------
|
| This item determines which server global should be used to retrieve the
| URI string.  The default setting of 'AUTO' works for most servers.
| If your links do not seem to work, try one of the other delicious flavors:
|
| 'AUTO'			Default - auto detects
| 'PATH_INFO'		Uses the PATH_INFO
| 'QUERY_STRING'	Uses the QUERY_STRING
| 'REQUEST_URI'		Uses the REQUEST_URI
| 'ORIG_PATH_INFO'	Uses the ORIG_PATH_INFO
|
*/
$config['uri_protocol']	= 'AUTO';

/*
|--------------------------------------------------------------------------
| URL suffix
|--------------------------------------------------------------------------
|
| This option allows you to add a suffix to all URLs generated by CodeIgniter.
| For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/urls.html
*/

$config['url_suffix'] = '';

/*
|--------------------------------------------------------------------------
| Default Language
|--------------------------------------------------------------------------
|
| This determines which set of language files should be used. Make sure
| there is an available translation if you intend to use something other
| than english.
|
*/
$config['language']	= 'english';

/*
|--------------------------------------------------------------------------
| Cache Directory Path
|--------------------------------------------------------------------------
|
| Leave this BLANK unless you would like to set something other than the default
| system/cache/ folder.  Use a full server path with trailing slash.
|
*/
$config['cache_path'] = '/opt/log/gsystem/cache/';

/*
|--------------------------------------------------------------------------
| Encryption Key
|--------------------------------------------------------------------------
|
| If you use the Encryption class or the Session class you
| MUST set an encryption key.  See the user guide for info.
|
*/
$config['encryption_key'] = 'ifchange';

/*
|--------------------------------------------------------------------------
| Cron Schedule Variables
|--------------------------------------------------------------------------
|
| 'enable_cron'                     = 是否开启cron schedule
| 'cron_schedule_table_name'        = 保存cron schedule的表
| 'cron_schedule_generate_every'    = 生成cron schedule的时间间隔
| 'cron_schedule_ahead_for'         = 每次产生多少时间内的cron schedule
| 'cron_schedule_lifetime'          = cron schedule的有效期
| 'cron_history_cleanup_every'      = 清除cron schedule的时间间隔
| 'cron_history_success_lifetime'   = 运行成功的cron schedule的保存时间
| 'cron_history_failure_lifetime'   = 运行失败的cron schedule的保存时间
|
*/
$config['enable_cron'] = TRUE;
$config['cron_schedule_table_name'] = 'schedules';
$config['cron_schedule_generate_every'] = 15;
$config['cron_schedule_ahead_for'] = 10;
$config['cron_schedule_lifetime'] = 15;
$config['cron_history_cleanup_every'] = 10;
$config['cron_history_success_lifetime'] = 60;
$config['cron_history_failure_lifetime'] = 600;

/*
|--------------------------------------------------------------------------
| Default Character Set
|--------------------------------------------------------------------------
|
| This determines which character set is used by default in various methods
| that require a character set to be provided.
|
*/
$config['charset'] = 'UTF-8';
$config['subclass_prefix'] = 'gsystem_';
$config['log_threshold'] = 6;
$config['language']      = 'english';
$config['charset']       = 'UTF-8';
$config['check_version'] = '/opt/wwwroot/check/version';
$config['tableMap']  = array(
        'school'                   => 'schools',
        'degree'                   => 'degrees',
        'dictionary'               => 'dictionaries',
        'gender'                   => 'genders',
        'language'                 => 'languages',
        'title'                    => 'titles',
        'title_alias'              => 'titles_aliases',
        'title_category'           => 'titles_categories',
        'function'                 => 'functions_cluster',
        'function_old'             => 'functions',
        'function_alias'           => 'functions_aliases',
        'function_category'        => 'functions_categories',
        'function_category_new'    => 'functions_categories_new',
        'function_keyword'         => 'functions_keywords',
        'function_knowledge'       => 'functions_knowledges',
        'function_special'         => 'functions_specials',
        'industry'                 => 'industries',
        'industry_alias'           => 'industries_aliases',
        'region'                   => 'regions',
        'account_basicpage'        => 'accounts_basicpages',
        'account_corporation'      => 'accounts_corporations',
        'account_industry'         => 'accounts_industries',
        'bdlist_alarm'             => 'bdlists_alarms',
        'bdlist_extra'             => 'bdlists_extras',
        'bdlist_link'              => 'bdlists_links',
        'bdlist_rc'                => 'bdlists_rcs',
        'corporation'              => 'corporations',
        'corporation_address'      => 'corporations_addresses',
        'corporation_alias'        => 'corporations_aliases',
        'corporation_baike'        => 'corporations_baikes',
        'corporation_baseinfo'     => 'corporations_baseinfos',
        'corporation_contact'      => 'corporations_contacts',
        'corporation_description'  => 'corporations_descriptions',
        'corporation_importance'   => 'corporations_importances',
        'corporation_industry'     => 'corporations_industries',
        'corporation_maturity'     => 'corporations_maturities',
        'corporation_nature'       => 'corporations_natures',
        'corporation_product'      => 'corporations_products',
        'corporation_product_cluster'      => 'corporations_product_cluster',
        'corporation_rc'           => 'corporations_rcs',
        'corporation_size'         => 'corporations_sizes',
        'corporation_title'        => 'corporations_titles',
        'corporation_type'         => 'corporations_types',
        'corporation_tag'          => 'corporations_tags',
        'customer'                 => 'customers',
        'customer_bdinfo'          => 'customers_bdinfos',
        'customer_employinfo'      => 'customers_employinfos',
        'customer_extra'           => 'customers_extras',
        'customer_function'        => 'customers_functions',
        'customer_note'            => 'customers_notes',
        'customer_salarystructure' => 'customers_salarystructures',
        'customer_team'            => 'customers_teams',
        'merchant_logo'            => 'merchants_logos',
        'merchant_permit'          => 'merchants_permits',
        'corporation_source'       => 'corporations_sources',
        'corporation_hr'           => 'corporations_hrs',
        'sync_spider'              => 'syncs_spiders',
        'city_pic_normal'          => 'city_pic_normal',
        'city_pic_special'         => 'city_pic_special',
		'record_log'               => 'records_logs',
		'corporation_name_inverted'=> 'corporations_names_inverted',
        );
$config['enable_hooks'] = TRUE;
$config['err_no'] = array(
        'gearman_work_fail'        => '5000001',
        'do_job_foreground_err'    => '5000002',
        'do_job_foreground_timeout'=> '5000003',
        'call_gearman'             => '5000004',

        'input_validate_err_no'     => '100001',
        'parameter_err_no'          => '100002',
        'db_err_no'                 => '100003',
        'row_not_exists_err_no'     => '100004',
        'exists_err_no'             => '100005',
        'permission_err_no'         => '100006',
        'file_size_err_no'          => '100007',
        'file_type_err_no'          => '100008',
        'file_upload_err_no'        => '100009',
        'file_not_exists_no'        => '100010',
        'login_err_no'              => '100011',
        'get_key_err_no'            => '100012',
        'data_exist_err_no'         => '100013',
        'parameter_repeat_err_no'   => '100014',
        'repeat_self_err_no'        => '100015',
        'delete_status_err_no'      => '100016',
        'delete_limit_err_no'       => '100017',
        'config_no_exists_err_no'   => '100018',
        'curl_err_no'               => '100019',

        'online_err_no'             => '100020',
        'remind_time_err_no'        => '100021',
        'socket_err_no'             => 100022,
        'receive_err_no'            => 100023,
        'pack_err_no'               => 100024,
        'config_no_exists_err_no'   => 100025,
        'cmd_err_no'                => 100026,
        'unpack_err_no'             => 100027,
        'input_parameter_err_no'    => '100028',
        'input_csv_error_no'        => '100029',
        'file_format_error_no'      => '100030',
        'open_uploaded_file_error_no'=> '100031',
        'move_tmpfile_error_no'     => '100032',
        'mkdir_error_no'            => '100033',
        'gbk2utf8_error_no'         => '100034',
        'all_lines_is_unvalid'      => '100035',
        'system_err_no'             => '100036',
        'deleted_err_no'            => '100037',
        'remark_err_no'             => '100038',
        'corporation_not_exist_err_no'=> '100039',
        'curl_res_err_no'           =>'100040',
        'write_file_error_no'       =>'100041',
        'word2pdf_error_no'         =>'100042',
        'word2txt_error_no'         =>'100043',
        'failured_reason_err_no'    =>'100044',
        'namelist_max_line_err_no'  =>'100045',
        'phone_tel_err_no'          =>'100046',
        'email_empty_err_no'        =>'100047',
        'name_empty_err_no'         =>'100048',
        'alias_name_repeat_err_no'  =>'100049',
        'in_blacklist_err_no'       =>'100050',
        'forbidden_err_no'            =>'100051',
        'interview_edit_err_no'    =>'100052',
        );
$config['err_msg']= array(
        5000001  => 'gearman_work_fail',
        5000002  => 'do_job_foreground_err',
        5000003  =>'do_job_foreground_timeout',
        5000004  =>'调用gearman失败！',
        '23000' => '该条目已经存在，请核实后再重新输入！',
        '100006'=> '您无权进行此操作，请联系你的上级！',
        '100002'=>'您输入的信息不完整，请核实后再重新输入！',
        '100001'=>'您输入格式有误，请核实后再重新输入！',
        '100003' =>'服务繁忙，请您先喝杯咖啡！',
        '100005'=>'该条目已经存在，请核实后再重新输入！',
        '100004'=> '该条目不存在，请进行其他操作！',
        '100007'=> '文件最大只能上传1k到2M!',
        '100008'=> '只能上传doc或docx格式的简历!',
        '100009'=> '上传失败！',
        '100010' =>'简历不存在，请联系相关负责人！',
        '100011' =>'认证失败，请重新登录！',
        '100012' =>'获取关键字失败！',
        '100013' =>'该数据不存在，或无权访问！',
        '100014' =>'该候选人已经存在，请联系逸橙团队！',
        '100015' =>'你有重复的候选人信息，请检查！',
        '100016' =>'请求参数有误，请重新操作！',
        '100017' =>'请求有误，请重新操作！',
        '100018' =>'配置文件不存在,请核实后再执行!',
        '100019' =>'发送http请求失败！',
        '100020' => '请启动客户端软件，否则无法登录!',
        '100021' =>'提醒时间必须大于当前时间',
        '100022' => 'Rpc server 连接失败！',
        '100023' => 'Rpc server 接收失败',
        '100024' => 'Rpc server 解包失败！',
        '100025' => 'Rpc server 配置文件不存在！',
        '100026' => 'Rpc server 连接失败！',
        '100027' => 'rpc server 解包失败！',
        '100028'=>'您输入的信息不完整，请核实后再重新输入！',
        '100029'=>'导入数据失败',
        '100030'=>'文件内容不符合规范',
        '100031'=>'打开文件失败，数据未能导入',
        '100032'=>'移动临时文件出错',
        '100033'=>'新建目录失败',
        '100034'=>'转换编码失败',
        '100035'=>'您输入的数据全部无效，请核实',
        '100036'=>'执行系统命令失败！',
        '100037'=>'该条目已经被删除！',
        '100038'=>'没有获取到备注的ID或类型！',
        '100039'=>'大客户不存在，请先到客户管理里添加大客户！',
        '100040'=>'curl返回错误！',
        '100041'=>'写文件失败！',
        '100042'=>'word转pdf错误！',
        '100043'=>'word转txt错误！',
        '100044'=>'请填写审核失败的原因！',
        '100045'=>'namelist不能超过2万条',
        '100046'=>'手机和座机必须填一个',
        '100047'=>'邮箱为空或格式错误',
        '100048'=>'姓名不能为空',
        '100049'=>'公司全名，简称或其他关键词有重复',
        '100050' =>'您已经进入了黑名单，请联系张CTO！',
        //'100051' =>'您查看联系方式权限被封杀，请联系张CTO！',
        '100051' =>'小样，手太贱了吧！',
        '100052' =>'请不要编辑他人的面试表格！',
		'400000' =>'开始时间和结束时间必填',
		'400001' =>'开始时间重复',
		'400002' =>'结束时间重复',
		'400003' =>'不能删除中间分类',
		'400004' =>'添加行业分类失败',
        '85042001' =>'输入不完整！',
        '85042002' =>'数据已存在！',
		'85042003' =>'行业名不能为空！',
		'85042004' =>'行业分类选择错误！',
		'85042005' =>'存在启用的子公司，不能禁用该公司',
		'85042006' =>'指向的父公司未启用',
		'85042007' =>'目标公司已关联到本公司',

		'85042008' =>'已存在同名的公司，且公司ID不相同',

		'85000000' =>'拒绝服务！',
        );
$config['sleep_us'] = 1000*1000*5;
$config['tmp_dir']  = '/opt/log/';

$config['notice_email'] = array(
    'jiqing.sun@cheng95.com',
);




$config['dictionaries']['area_name'] = array(
        '0' => '国家',
        '1' => '省级单位',
        '2' => '市级单位',
        );
$config['dictionaries']['is_deleted'] = array(
        'Y'=>'已删除',
        'N' => '有效',
        );
$config['dictionaries'] ['gender'] = array(
 '请选择...',
 'M'=>'男',
 'F'=>'女',
 'U'=>'未知',
 );
$config['dictionaries']['source'] = array(1=>'智联招聘',2=>'前程无忧',3=>'猎聘网',
        /*4=>'',5=>'',*/6=>'建筑英才网',7=>'中国人才热线',8=>'锐士方达',9=>'中华英才网',10=>'MP',
        '15'=>'南方人才网(job168)',16=>'unknown(out)', 17=>'unknown(yangs)',18=>'宁波人才网','19'=>'赢商人才', 97=>'weixin', 98=>'easyhunter', 99=>'ifchange'
        );
$config['dictionaries']['expect_work_at'] = array(
        '即时'=>'即时',
        '一周以内'=>'一周以内',
        '一个月内'=>'一个月内',
        '1-3个月'=>'1-3个月',
        '三个月后'=>'三个月后' ,
        '待定'=>'待定',
        );
$config['dictionaries']['is_fertility'] = array('U'=>'', 'Y'=>'已育', 'N'=>'未育');
$config['dictionaries']['overseas'] = array('U'=>'', 'Y'=>'有海外工作/学习经历', 'N'=>'无海外工作/学习经历');
$config['dictionaries']['level'] = array("一般" =>"一般"  ,
        "良好" =>"良好"  ,
        "熟练" =>"熟练"  ,
        "精通" =>"精通"  ,
        'basic'     =>'basic'      ,
        'average'   =>'average'    ,
        'proficient'=>'proficient'  ,
        'expert'    =>'expert'     ,
        );
$config['dictionaries']['is_house']     = array('U'=>'', 'Y'=>'是', 'N'=>'否');
$config['dictionaries']['live_family']  = array('U'=>'', 'Y'=>'是', 'N'=>'否');
$config['dictionaries'] ['menu'] = array('our_users'=>'用户管理','our_roles'=>'角色管理', 'our_grants'=>'权限管理',
        'our_offices'=>'office管理','our_teams'=>'团队管理', 'our_positions'=>'职称管理',
        'our_questions'=>'反馈管理', 'disciplines'=>'专业管理', 'teletexts'=>'系统设置',
        'schools'=>'高校管理','mailboxes'=>'邮箱管理',
        //'cities'=>'城市管理'
        );
$config['dictionaries'] ['menu2'] = array(
        'candidates'=>array(
            'name'=>'候选人管理', 'path'=>'candidate', 'member'=>array('collections', 'attachments', 'candidates', 'namelists')
            ),
        'classifications'=>array(
               'path'=>'candidate','name'=>'候选人管理', 'member'=>array('classifications')
               ),
        'positions'=>array(
               'path'=>'position','name'=>'职位管理', 'member'=>array('positions')
               ),
        'corporations'=>array(
               'path'=>'corporation','name'=>'客户管理', 'member'=>array('corporations')
               ),
        'bdlists'=>array(
               'path'=>'bdlist','name'=>'BD List', 'member'=>array('bdlists')
               ),
		 'entry_teams'  => array(
                'path'=>'station','name'=>'定制管理', 'member'=>array('entry_teams','stations','station_unmatches','cyclopaedias')
               ),
        );
$config['dictionaries'] ['menu3'] = array(
        'analyzers'=>array(
               'path'=>'analyzer','name'=>'简历解析', 'member'=>array('analyzers'),'type'=>array(1=>'简历解析')
         )
        );
$config['dictionaries']['model_sort'] = array(
        '1'=>'oa','2'=>'hunter','3'=>'mail','4'=>'cms','5'=>'2B','6'=>'2C','7'=>'cv',8=>'reminds', '9'=>'gallery','10'=>'smis', 11=>'cv-search',
        );
$config['dictionaries']['common_functions'] = array(
        "181"=>"销售"         ,
        "191"=>"客服"         ,
        "196"=>"人力资源"     ,
        "205"=>"行政"         ,
        "210"=>"市场"         ,
        "220"=>"媒介"         ,
        "225"=>"公共关系"     ,
        "230"=>"战略规划"     ,
        "231"=>"投资并购"     ,
        "247"=>"法务"         ,
        );
// 婚姻状况配置
$config['dictionaries']['marital'] = array('请选择...', '1'=>'未婚', '2'=>'已婚',);
$config['dictionaries']['contract'] = array('请选择...', '1'=>'1年', '2'=>'2年', 3=>'3年');

// 学历配置
$config['dictionaries']['degree'] = array('请选择...','1'=>'普通本科', '2'=>'211本科', '3'=>'硕士', '4'=>'博士', '5'=>'专科', '6'=>'其他');
$config['dictionaries']['question_type']  = array(
        '请选择...',
        'Bug类(系统错误，哪些功能无法实现，系统无法响应等)',
        '功能类(哪些功能不完善，需要添加哪些功能。以及相应的修改建议)',
        '体验类(哪些功能使用体验不好，以及相应的修改建议)',
        '流程类(哪些流程设置有问题，以及相应的修改建议)',
        );
$config['dictionaries']['question_level'] = array('请选择...','高','中','低');
$config['dictionaries']['department'] = array('请选择...',
        '教育部'=>'教育部',
        '上海市'=>'上海市',
        '上海市教委'=>'上海市教委',
        '上海市教育委员会'=>'上海市教育委员会',
        '上海应用技术学院'=>'上海应用技术学院',
        '上海理工大学'=>'上海理工大学',
        '中华全国总工会'=>'中华全国总工会',
        '中国人民解放军信息工程大学'=>'中国人民解放军信息工程大学',
        '中国人民解放军总政治部'=>'中国人民解放军总政治部',
        '中国地震局'=>'中国地震局',
        '中国民用航空总局'=>'中国民用航空总局',
        '中国科学院'=>'中国科学院',
        '中央军委'=>'中央军委',
        '中央办公厅'=>'中央办公厅',
        '云南省'=>'云南省',
        '云南省教育厅'=>'云南省教育厅',
        '交通运输部'=>'交通运输部',
        '全国妇联'=>'全国妇联',
        '公安部'=>'公安部',
        '共青团中央'=>'共青团中央',
        '内蒙古'=>'内蒙古',
        '内蒙古教育厅'=>'内蒙古教育厅',
        '内蒙古自治区教育厅'=>'内蒙古自治区教育厅',
        '北京'=>'北京',
        '北京市'=>'北京市',
        '北京市商务委员会'=>'北京市商务委员会',
        '北京市教委'=>'北京市教委',
        '北京市教育委员会'=>'北京市教育委员会',
        '华东师范大学'=>'华东师范大学',
        '司法部'=>'司法部',
        '吉林省'=>'吉林省',
        '吉林省教育厅'=>'吉林省教育厅',
        '哈尔滨工业大学'=>'哈尔滨工业大学',
        '四川省'=>'四川省',
        '四川省教育厅'=>'四川省教育厅',
        '国侨办'=>'国侨办',
        '国家安监总局'=>'国家安监总局',
        '国家林业局'=>'国家林业局',
        '国家民委'=>'国家民委',
        '国防部'=>'国防部',
        '天津市'=>'天津市',
        '天津市教委'=>'天津市教委',
        '天津市教育委员会'=>'天津市教育委员会',
        '宁夏'=>'宁夏',
        '宁夏回族自治区教育厅'=>'宁夏回族自治区教育厅',
        '安徽省'=>'安徽省',
        '安徽省教育厅'=>'安徽省教育厅',
        '山东省'=>'山东省',
        '山东省人民政府'=>'山东省人民政府',
        '山东省教育厅'=>'山东省教育厅',
        '山西医科大学'=>'山西医科大学',
        '山西省'=>'山西省',
        '山西省教育厅'=>'山西省教育厅',
        '工业和信息化部'=>'工业和信息化部',
        '广东省'=>'广东省',
        '广东省教育厅'=>'广东省教育厅',
        '广西'=>'广西',
        '广西壮族自治区教育厅'=>'广西壮族自治区教育厅',
        '广西教育厅'=>'广西教育厅',
        '广西省教育厅'=>'广西省教育厅',
        '惠州市政府'=>'惠州市政府',
        '成都市人民政府'=>'成都市人民政府',
        '新加坡莱佛士教育集团'=>'新加坡莱佛士教育集团',
        '新疆'=>'新疆',
        '新疆生产建设兵团'=>'新疆生产建设兵团',
        '新疆维吾尔自治区教育厅'=>'新疆维吾尔自治区教育厅',
        '民航总局'=>'民航总局',
        '江苏省'=>'江苏省',
        '江苏省教育厅'=>'江苏省教育厅',
        '江西教育厅'=>'江西教育厅',
        '江西省'=>'江西省',
        '江西省教育厅'=>'江西省教育厅',
        '河北师范大学'=>'河北师范大学',
        '河北省'=>'河北省',
        '河北省教育厅'=>'河北省教育厅',
        '河南省'=>'河南省',
        '河南省卫生厅'=>'河南省卫生厅',
        '河南省教育厅'=>'河南省教育厅',
        '浙江浙大城市学院教育发展股份有限公司'=>'浙江浙大城市学院教育发展股份有限公司',
        '浙江省'=>'浙江省',
        '浙江省教育厅'=>'浙江省教育厅',
        '海关总署'=>'海关总署',
        '海南省'=>'海南省',
        '海南省教育厅'=>'海南省教育厅',
        '湖北省'=>'湖北省',
        '湖北省教育厅'=>'湖北省教育厅',
        '湖南大学'=>'湖南大学',
        '湖南教育厅'=>'湖南教育厅',
        '湖南省'=>'湖南省',
        '湖南省教育厅'=>'湖南省教育厅',
        '甘肃省'=>'甘肃省',
        '甘肃省教育厅'=>'甘肃省教育厅',
        '福建省'=>'福建省',
        '福建省教育厅'=>'福建省教育厅',
        '西藏'=>'西藏',
        '解放军总政治部'=>'解放军总政治部',
        '贵州省'=>'贵州省',
        '贵州省教育厅'=>'贵州省教育厅',
        '辽宁省'=>'辽宁省',
        '辽宁省教育厅'=>'辽宁省教育厅',
        '重庆市'=>'重庆市',
        '重庆市教委'=>'重庆市教委',
        '重庆市教育委员会'=>'重庆市教育委员会',
        '陕西省'=>'陕西省',
        '陕西省教育厅'=>'陕西省教育厅',
        '青海省'=>'青海省',
        '青海省教育厅'=>'青海省教育厅',
        '香港特别行政区'=>'香港特别行政区',
        '高顿教育集团'=>'高顿教育集团',
        '黑龙江省'=>'黑龙江省',
        '黑龙江省教育厅'=>'黑龙江省教育厅',

        );
$config['dictionaries']['area']= array(
        //0 =>'全球',
        //1 => '中国',
        2 =>'北京',
        3 =>'天津',
        4 =>'河北',
        5 =>'山西',
        6 =>'内蒙古',
        7 =>'辽宁',
        8 =>'吉林',
        9 =>'黑龙江',
        10 =>'上海',
        11 =>'江苏',
        12 =>'浙江',
        13 =>'安徽',
        14 =>'福建',
        15 =>'江西',
        16 =>'山东',
        17 =>'河南',
        18 =>'湖北',
        19 =>'湖南',
        20 =>'广东',
        21 =>'广西',
        22 =>'海南',
        23 =>'重庆',
        24 =>'四川',
        25 =>'贵州',
        26 =>'云南',
        27 =>'西藏',
        28 =>'陕西',
        29 =>'甘肃',
        30 =>'青海',
        31 =>'宁夏',
        32 =>'新疆',
        3905 =>'澳门',
        3907 =>'香港',
        3954 =>'台湾',
        3956 =>'海外',
        );
$config['dictionaries']['political_status']= array(
        '中共党员'=>'中共党员',
        '党员'=>'党员',
        '中共党员(含预备党员)'=>'中共党员(含预备党员)',  
        '团员'=>'团员', 
        '群众'=>'群众', '民主党派'=>'民主党派', '无党派人士'=>'无党派人士', '无可奉告'=>'无可奉告',
        'Party Member'=>'Party Member','League member'=>'League member',
        'Citizenship'=>'Citizenship','Party'=>'Party','No Party'=>'No Party','none'=>'none',
        );

//候选人 公司 职位 自定义字段选择项 1 候选人 2 公司 3 职位
$config['dictionaries']['candidate_option_list']= array(
        '1'=>array(
                'name'=>'真实姓名',
                'gender'=>'性别',
                'corporation_name'=>'所在公司',
                'architecture_name'=>'所在部门',
                'work_type'=>'职能',
                'phone'=>'手机',
                'tel'=>'座机',
                'degree'=>'学历',
                'work_experience'=>'工作年限',
                'position_name'=>'职位名称',
                //'industry_name'=>'行业类别',
                //'station_name'=>'岗位类别',
                'title_name'=>'职级',
                'management_experience'=>'管理经验',
                'start_time'=>'加入当前公司时间',
                'current_status'=>'目前状态',
                'email'=>'邮箱',
                'qq'=>'QQ',
                'msn'=>'MSN',
                'sina'=>'新浪微博',
                'ten'=>'腾讯微博',
                'school_name'=>'学校',
                'discipline_name'=>'专业',
                'basic_salary'=>'月薪(K)',
                'expect_salary'=>'期望月薪(K)',
                'annual_salary'=>'年薪(K)',
                'expect_annual_salary'=>'期望薪资(K)',
                'address'=>'现住地',
                'account'=>'籍贯',
                'my_project'=>'定向Search',
                'marital'=>'是否已婚',
                'is_fertility'=>'是否已育',
                'is_house'=>'居住地有无购房',
                'live_family'=>'是否与家人同住',
                'expect_city_names' => '期望工作地',
                'is_remark'=>'Y',
        //		'updated_at'=>'修改时间',
            ),
        '2'=>array(
                'name'=>'公司名称',
                'created_on'=>'创立时间',
                'number'=>'员工总数',
                'headquarters_city'=>'总部城市',
                'renwu'=>'代表人物',
                'candidate_id'=>'联系人',
                'is_reviewed'=>'审核情况',
                'user_name'=>'录入者',
            ),
        '3'=>array(
                'name'=>'职位名称',
                'corporation_name'=>'所属公司',
                'architecture_name'=>'所属部门',
                'title_name'=>'职级',
                'number'=>'招聘人数',
                'salary'=>'年薪(K)',
                'subordinate_num'=>'下属人数',
                'is_manager'=>'管理岗位',
                'sex'=>'性别',
                'is_new'=>'职位类型',
                'experience_years'=>'工作年限',
                'leader'=>'汇报对象',
                'leader_title_name'=>'汇报对象级别',
                'degree'=>'学历',
                'team_size'=>'团队规模',
                'work_cities_names'=>'工作地',
                'user_name'=>'录入者',
                'created_at'=>'录入时间',
                'hope_entry_time'=>'期望入职时间',
                'status'=>'职位状态',
                'demand_level'=>'内部分类',

            ),
        '4' => array(
            'corporation_name' => '公司名称',
            'corporation_alias_name' => '标准简称',
            'tel'           => '公司总机',
            'hunter_name'  => '猎头负责人',
            'hunter_mobile' => '手机',
            'business_type_value' => '客户成熟度',
            'importance_value'    => '客户重要度',
            'updated_at'    => '上次联系时间',
            'email'              => '公司邮箱',
            'home'          => '公司网址',
            'address'       => '公司地址',
            'hunter_position'  => '猎头负责人职位',
            'hunter_qq'        => 'QQ',
            'hunter_msn'       => 'MSN',
            'hunter_weibo'     => 'Weibo',
            'city_name'     => '总部城市',
            'type_name'     => '公司性质',
            'scale_name'    => '公司规模',
            'industry_type_value' => '所属行业',
            'description'   => '公司简介',
            'recruitment1'   => '是否使用猎头',
            'recruitment2'   => '是否使用网络招聘',
            'recruitment3'   => '是否使用RPO',
            'is_edited'   => '状态',
            ),
        );

$config['dictionaries']['candidate_option_list_1']= array(
        'name'=>'姓名',
        'corporation_name'=>'公司名称',
        'architecture_name'=>'所在部门',
        'address'=>'现住地',
        'industry_name'=>'行业类别',
        'station_name'=>'岗位类别',
        'work_experience'=>'工作年限',
        'degree'=>'学历',
        'phone'=>'电话',
        );
$config['dictionaries']['corporation_option_list_2']= array(
        'alias_name'=>'标准简称',
        'headquarters_city'=>'总部城市',
        'created_on'=>'创立时间',
        'number'=>'员工总数',
        'candidate_id'=>'联系人',
        'user_name'=>'录入者',
        );
$config['dictionaries']['position_option_list_3']= array(
        'name'=>'职位名称',
        'corporation_name'=>'所属公司',
        'architecture_name'=>'所在部门',
        'user_name'=>'录入者',
        'sex'=>'性别',
        'work_cities_names'=>'工作地',
        'experience_years'=>'工作年限',
        'degree'=>'学历',
        );
$config['dictionaries']['bdlist_option_list_4']= array(
        'corporation_name'=>'公司名称',
        'corporation_alias_name'=>'标准简称',
        'tel'=>'公司总机',
        'hunter_name'=>'猎头业务负责人',
        'hunter_mobile'=>'手机',
        'business_type_value'   => '客户成熟度',
        'importance_value'      => '客户重要度',
        'updated_at'      => '上次联系时间',
        'email'           => '公司邮箱',
        'home'            => '公司网址',

        );
$config['dictionaries']['customs_select_list']= array(
    '1' => array(
            '0' => array('key' => 'name', 'name'=>'姓名'),
            '1' => array('key' => 'corporation_name', 'name' => '公司名称'),
            '2' => array('key' => 'architecture_name', 'name' =>'所在部门'),
            '3' => array('key' => 'address', 'name' => '现住地'),
            '4' => array('key' => 'phone', 'name' => '手机'),
            '5' => array('key' => 'email', 'name' => 'E-mail'),
            '6' => array('key' => 'work_experience', 'name' => '工作年限'),
            '7' => array('key' => 'degree', 'name' => '学历'),
            '8' => array('key' => 'expect_salary', 'name' =>'期望月薪(k)'),
        ),
    '2' => array(
            '0' => array('key' => 'alias_name', 'name'=>'标准简称'),
            '1' => array('key' => 'headquarters_city', 'name'=>'总部城市'),
            '2' => array('key' => 'created_on', 'name'=>'创立时间'),
            '3' => array('key' => 'number', 'name'=>'员工总数'),
            '4' => array('key' => 'candidate_id', 'name'=>'联系人'),
            '5' => array('key' => 'user_name', 'name'=>'录入者'),
        ),
    '3' => array(
            '0' => array('key' => 'name', 'name'=>'职位名称'),
            '1' => array('key' => 'corporation_name', 'name'=>'所属公司'),
            '2' => array('key' => 'architecture_name', 'name'=>'所在部门'),
            '3' => array('key' => 'user_name', 'name'=>'录入者'),
            '4' => array('key' => 'sex', 'name'=>'性别'),
            '5' => array('key' => 'work_cities_names', 'name'=>'工作地'),
            '6' => array('key' => 'experience_years', 'name'=>'工作年限'),
            '7' => array('key' => 'degree', 'name'=>'学历'),
        ),
);
$config['dictionaries']['credit_category']= array(
    'I'=>'收入',
    'O'=>'支出',
);

$config['dictionaries'] ['menu'] = array('our_users'=>'用户管理','our_roles'=>'角色管理', 'our_grants'=>'权限管理',
        'our_offices'=>'office管理','our_teams'=>'团队管理', 'our_positions'=>'职称管理',
        'our_questions'=>'反馈管理', 'disciplines'=>'专业管理', 'teletexts'=>'系统设置',
        'schools'=>'高校管理',
        //'cities'=>'城市管理'
        );
$config['dictionaries'] ['menu2'] = array(
        'candidates'=>array(
               'path'=>'candidate','name'=>'候选人管理', 'member'=>array('collections', 'attachments', 'candidates', 'namelists')
               ),
        'classifications'=>array(
               'path'=>'candidate','name'=>'候选人管理', 'member'=>array('classifications','attachments')
               ),
        'positions'=>array(
               'path'=>'position','name'=>'职位管理', 'member'=>array('positions')
               ),
        'corporations'=>array(
               'path'=>'corporation','name'=>'客户管理', 'member'=>array('corporations')
               ),
        'bdlists'=>array(
               'path'=>'bdlist','name'=>'BD List', 'member'=>array('bdlists')
               ),
        'entry_teams'  => array(
                'path'=>'station','name'=>'定制管理', 'member'=>array('entry_teams','stations','station_unmatches','cyclopaedias')
               ),
       
        );
$config['dictionaries'] ['menu3'] = array(
        'analyzers'=>array(
               'path'=>'analyzer','name'=>'简历解析', 'member'=>array('analyzers'),'type'=>array(1=>'简历解析')
         )
        );
// 内部系统 任务级别
$config['dictionaries']['task_levels'] = array('1'=>'高', '2'=>'中', '3'=>'低');
// 内部系统 任务状态
$config['dictionaries']['task_status'] = array('1'=>'未处理', '2'=>'处理中', '3'=>'反馈', '4'=>'已完成');

// 是否配置
$config['dictionaries']['yes_or_no'] = array('U'=>'', 'Y'=>'是', 'N'=>'否');

// 性别配置
$config['dictionaries']['gender'] = array('M'=>'男', 'F'=>'女', 'U'=>'未知');

// 婚姻状况配置
$config['dictionaries']['marital'] = array('U'=>'', 'Y'=>'已婚', 'N'=>'未婚');

// 学历配置
$config['dictionaries']['degree'] = array('1'=>'本科','2'=>'硕士',6=>'MBA', '94'=>'EMBA', 95=>'MPA','3'=>'博士',10=>'博士后', '92'=>'专升本','4'=>'专科', 90=>'中专','91'=>'中技', '86'=>'初中', 87=>'职高',89=>'高中',99=>'其他');
/*
 高中   High School
 中技   Technical school_name
 中专   Vocational School
 专科   Associate 
 专升本 
 本科   bachelor
 硕士   Master
 MBA    MBA 
 EMBA   EMBA
 MPA    MPA
 博士   Doctor/Ph.D
*/
// 学历配置
$config['dictionaries']['degree_above'] = array(
        89 => array(89,90,91,87,4,92,1,2,3,10),
        90 => array(89,90,91,87,4,92,1,2,3,10),

        91 => array(91,4,87,92,1,2,3,10),

        92 => array(92,1,2,3,10),

        4   => array(4,87,92,1,2,3,10),
        87  => array(4,87,92,1,2,3,10),

        1   => array(1,2,3,10),

        2   => array(2,6,94,95,3,10),
        6   => array(2,6,94,95,3,10),
        94  => array(2,6,94,95,3,10),
        95  => array(2,6,94,95,3,10),
        3  => array(3,10),
        10 => array(10),
        );

// 合同期限
$config['dictionaries']['contract'] = array('0'=>'', '1'=>'一年', '2'=>'三年', '3'=>'六年');

//职位类型
$config['dictionaries']['is_new'] = array('Y'=>'新增','M'=>'替补','O'=>'未知');

//职位审核定义
$config['dictionaries']['p_is_reviewed'] = array('Y'=>'通过审核','N'=>'未通过审核','U'=>'待审核','I'=>'待完善');

//职位状态
$config['dictionaries']['p_status'] = array('R'=>'进展中','P'=>'pending','D'=>'放弃');

//是否有面试
$config['dictionaries']['is_pagetest'] = array('Y'=>'有','N'=>'无','O'=>'未知');

// 候选人目前状况
$config['dictionaries']['current_status'] = array( '1'=>'离职，正在看机会', '2'=>'在职，正在看机会', '3'=>'在职，有好的机会可以考虑', '4'=>'在职，不考虑机会', '5'=>'应届毕业生');

// 候选人工作年限
$config['dictionaries']['work_experience'] = array('1'=>'1年', '2'=>'2年', '3'=>'3年', '4'=>'4年', '5'=>'5年', '6'=>'6年', '7'=>'7年', '8'=>'8年', '9'=>'9年', '10'=>'10年', '11'=>'11年', '12'=>'12年', '13'=>'13年', '14'=>'14年', '15'=>'15年', '16'=>'16年', '17'=>'17年', '18'=>'18年', '19'=>'19年', '20'=>'20年');

for ($iw=1; $iw<60; $iw++) {
    $config['dictionaries']['work_experience'][$iw] = $iw.'年';
}

// 推荐候选人状态
$config['dictionaries']['recommend_status'] = array('1'=>'等待主管审核', '2'=>'主管审核未通过', '3'=>'等待接口人审核', '4'=>'接口人审核未通过', '5'=>'等待客户审核', '6'=>'客户审核未通过', '7'=>'初试', '8'=>'复试', '9'=>'终试', '10'=>'offer', '11'=>'待开票', '12'=>'结束', '13'=>'终止');

// 可入职时间
$config['dictionaries']['entry_time'] = array('0'=>'', '1'=>'一周内', '2'=>'两周内', '3'=>'一个月内', '4'=>'一个月以上');

// 出生日期 - 年
$eff_year_from = date('Y', time()) - 16;
$eff_year_to = date('Y', time()) - 60;
for($i = $eff_year_from; $i > $eff_year_to; $i--) {
    $eff_year_arr[$i] = $i.'年';
}
$config['dictionaries']['birth_year'] = $eff_year_arr;

// 出生日期 - 月
$config['dictionaries']['birth_month'] = array('1'=>'1月', '2'=>'2月', '3'=>'3月', '4'=>'4月', '5'=>'5月', '6'=>'6月', '7'=>'7月', '8'=>'8月', '9'=>'9月', '10'=>'10月', '11'=>'11月', '12'=>'12月');

//公司性质
$config['dictionaries']['corporation_types'] = array('1'=>'国企', '2'=>'外企', '3'=>'上市公司', '4'=>'非上市公司');

//是否签约
$config['dictionaries']['is_contract'] = array('Y'=>'已签约', 'N'=>'未签约');
$config['dictionaries']['is_deleted'] = array('N'=>'open', 'Y'=>'关闭');

//职位状体
$config['dictionaries']['position_statuses'] = array('Y'=>'close', 'N'=>'open');

//收费方式
$config['dictionaries']['fee_manners'] = array('1'=>'一次性收费', '2'=>'分批收费');
$config['dictionaries']['fee_proportions'] = array('1'=>'统一收费', '2'=>'分档收费');

//公司规模
$config['dictionaries']['corporation_scales'] = array(
        "1"=>'少于50人',
        "2"=>'50-150人',
        "3"=>'150-500人',
        "4"=>'500-1000人',
        "5"=>'1000-5000人',
        "6"=>'5000-10000人',
        "7"=>'10000人以上',
        );

//工作年限
$config['dictionaries']['experiences'] =array(
        1=>'一年以下',
        2=> '一年以上两年以下',
        3=>'三年以上',
        );
$config['dictionaries']['position_types'] = array('Y'=>'新增', 'N'=>'替补', 'O'=>'未知');
//团队规模
$config['dictionaries']['team'] =array(
        1=>'大',
        2=>'中',
        3=>'小',
        );

/********** 面试表格 *************/

// 工作表现
$config['dictionaries']['responsibilities'] =array(
    1=>'是公司或者部门表现最好的',
    2=>'表现尚可',
    3=>'表现一般',
    4=>'表现不佳',
);

// 下属团队
$config['dictionaries']['subordinates_count'] =array(
    1=>'0',
    2=>'1-10人',
    3=>'10-30人',
    4=>'30人-50人',
    4=>'50-100',
    4=>'100人以上',
);

// 跳槽最关键的原因
$config['dictionaries']['changereason_type'] =array(
    1=>'更好的薪水',
    2=>'更高的职位',
    3=>'更好的公司或者产品',
    4=>'有机会从事自己喜欢的工作',
    5=>'遭到不公正的待遇',
    6=>'原来的同事或者老板邀请',
    7=>'自己创业',
    8=>'和同事关系不好',
    9=>'公司的原因(指倒闭或者职位调整)',
    10=>'地点靠家更近',
    11=>'其他原因(请注明)',
);

// 考虑外部机会的原因
$config['dictionaries']['opportunity_type'] =array(
    1=>'追求更好的薪水',
    2=>'追求更高的职位',
    3=>'追求更好的公司',
    4=>'追求更好的项目',
    5=>'当前公司项目发展不好',
    6=>'当前公司效益不好/有裁员计划',
    7=>'当前和同事关系相处不好',
    8=>'个人在当前公司发展不好',
    9=>'想离家更近',
    10=>'寻找更加朝阳的行业',
    11=>'其它',
);

// 对本次推荐的工作最看重什么
$config['dictionaries']['whatimportant_type'] =array(
    1=>'对这个公司比较认同',
    2=>'对这个职位的工作内容比较有兴趣',
    3=>'对这个职位的薪资福利待遇比较看好',
    4=>'有兴趣看外面机会，所以各种机会都接触下看看',
    5=>'对这个项目/部门/负责人比较看好',
    6=>'猎头/HR/业务部门太热情诚恳，不好意思拒绝',
    7=>'行业不错',
    8=>'地点不错',
    9=>'其它',
);

// 你当初为什么加入到目前的这个公司
$config['dictionaries']['join_this_reason_type'] =array(
    1=>'喜欢这个行业',
    2=>'喜欢这个公司',
    3=>'喜欢这份职业',
    4=>'被邀请过来',
    5=>'被推荐过来',
    6=>'薪水高',
    7=>'职位高',
    8=>'不了解这个公司，稀里糊涂被骗进来了',
    9=>'第一份工作',
    10=>'和老板有关系',
    11=>'其他(请注明)',
);

// 你觉得在目前的工作最让你留恋的是什么
$config['dictionaries']['work_you_love_type'] =array(
    1=>'领导',
    2=>'同事',
    3=>'公司工作氛围',
    4=>'公司发展前景',
    5=>'工作环境/地点',
    6=>'福利',
    7=>'培训机制',
    8=>'公司品牌',
    9=>'其他(请注明)',
);

// 有没有参加过其他面试
$config['dictionaries']['other_interview'] =array(
    1=>'没有参加面试',
    2=>'有面试，没offer',
    3=>'有offer',
);

// 没去的原因
$config['dictionaries']['participated_company_type'] =array(
    1=>'面试没通过',
    2=>'薪资没谈拢',
    3=>'原公司挽留',
    4=>'家人反对',
    5=>'其他',
);

// 公司会如何挽留你
$config['dictionaries']['hold_you_type'] =array(
    1=>'加薪',
    2=>'升职',
    3=>'换一份更好的工作',
    4=>'冷处理(找各种理由拖延)',
    5=>'启动法律程序',
    6=>'象征性的挽留一下',
    7=>'不挽留',
    8=>'推心置腹的挽留，突出你的重要地位',
    9=>'情感挽留',
    10=>'已经离职/确定会离职',
    11=>'其他',
);

// 你会咨询谁
$config['dictionaries']['consult_type'] =array(
    1=>'家人',
    2=>'现在的老板',
    3=>'现在公司的同事',
    4=>'同学，知心的朋友',
    5=>'以前的老板或者同事',
    6=>'其他(请注明)',
);

// 最容易被何种方式打动  、 在何种情况下你会选择留下来
$config['dictionaries']['move_way_type'] =array(
    1=>'加薪',
    2=>'升职',
    3=>'换一份更有意思的工作',
    4=>'老板的恳求',
    5=>'已经离职/确定会离职',
    6=>'其他',
);

// 可否提供薪金证明
$config['dictionaries']['salary_proof'] =array(
    1=>'工资条',
    2=>'offer letter',
    3=>'银行存折打印凭条',
    4=>'HR证明',
    5=>'其他',
);

// 推荐状态
$config['dictionaries']['recommend'] =array(
    1=>'等待主管审核',
    2=>'等待接口人审核',
    3=>'等待客户审核',
    4=>'等待面试',
    5=>'等待复试',
    6=>'等待终试',
    7=>'等待入职',
    8=>'等待开票',
    9=>'已完成',
    10=>'主管审核未通过',
    11=>'接口人审核未通过',
    12=>'客户审核未通过',
    13=>'初试未通过',
    14=>'复试未通过',
    15=>'终试未通过',
    16=>'拒绝offer',
);
/********** 面试表格 *************/
$config['dictionaries']['resume_hunter_tpl']= 'resume_hunter.docx';
$config['dictionaries']['resume_templates']= '/opt/wwwroot/rd/easyhunter/hunter/config/';


$config['dictionaries']['area_name'] = array(
        '0' => '国家',
        '1' => '省级单位',
        '2' => '市级单位',
        );
$config['dictionaries']['is_deleted'] = array(
        'Y'=>'已删除',
        'N' => '有效',
        );

$config['dictionaries']['area']= array(
        //0 =>'全球',
        //1 => '中国',
        2 =>'北京',
        10 =>'上海',
        20 =>'广东',
        11 =>'江苏',
        12 =>'浙江',
        24 =>'四川',
        3 =>'天津',
        18 =>'湖北',
        19 =>'湖南',
        23 =>'重庆',
        28 =>'陕西',
        16 =>'山东',
        5 =>'山西',
        13 =>'安徽',
        15 =>'江西',
        17 =>'河南',
        4 =>'河北',
        14 =>'福建',

        9 =>'黑龙江',
        8 =>'吉林',
        7 =>'辽宁',

        22 =>'海南',
        21 =>'广西',
        25 =>'贵州',
        26 =>'云南',

        6 =>'内蒙古',
        29 =>'甘肃',
        31 =>'宁夏',
        32 =>'新疆',
        30 =>'青海',
        27 =>'西藏',
        3905 =>'澳门',
        3907 =>'香港',
        3954 =>'台湾',
        3956 =>'海外',
        );

// bdlist相关 corporation
$config['dictionaries']['corporation'] = array(
    // 公司类型
    'business_type' => array(
        '1' => array('1' => '客户端游戏', '2' => '网页游戏', '3'=>'手机游戏'),
        //'2' => array('100' => '', '101'=>'1-100', '102' => '101-200'),
    ),
    // 公司招聘方式
    'recruitment' => array(
        '1' => '猎头招聘',
        '2' => '网络招聘',
        '3' => 'RPO',
    ),

);

// 公司性质
$industry_type = array(
    '1' => array('a' => '', '1' => '上市公司', '2' => '非上市公司' , '3'=>'外企'),
    '2' => array('a' => '', '101' => '民营企业', '102' => '合资企业','103' => '外资企业'),
    '3' => array('a' => '', '201' => '国有企业', '202' => '外资企业', '203'=>'上市公司', '204'=>'非上市公司'),
    '4' => array('a' => '', '301'=>'500强', '302'=>'外资', '303'=>'内资'),
);
// 公司规模
$industry_scale = array(
    '1' => array('a' =>'',  '1'   => '100人以下', '2' => '100-500人', '3'=>'500-1000人', '4'=>'1000人以上'),
    '2' => array('a' => '', '101' =>'200人以下', '102' => '200－1000人', '103'=>'1000－5000人', '104'=>'5000人以上'),
    '3' => array('a' => '', '201' =>'500人以下', '202'=>'500－1000人', '203'=>'1000－5000人', '204'=>'5000人以上'),
    '4' => array('a' => '', '301' =>'20人以下', '302'=>'20-50人', '303'=>'50-99人', '304'=>'100-199人', 
        '305'=>'200-499人', '306'=>'500人-999人', '307'=>'1000人以上'),
    '5' => array('a' => '', '401' =>'100以下', '402'=>'100-499', '403'=>'500-999', '404'=>'1000-2999', '405'=>'3000以上'),
);

// 网络游戏，搜索， 云计算， 互联网广告
$type_key = array(
    '5'=>'1', '23'=>'1', '24'=>'1', '25'=>'1','26'=>'2', '27'=>'3',
    '28' =>'4', '29'=>'4', '30'=>'4', '31'=>'4', '32'=>'4', '33'=>'4', '34'=>'4', '35'=>'4', '36'=>'4', '37'=>'4', 
    '38'=>'4', '39'=>'4', '40'=>'4', '41'=>'4', '42'=>'4', '43'=>'4',
);
foreach ($type_key as $k => $v) {
    $config['dictionaries']['corporation']['type'][$k] = $industry_type[$v];
}

$scale_key = array(
    '5'=>'1', '23'=>'2', '24'=>'3', '25'=>'1','26'=>'4', '27'=>'5','28' =>'1', '29'=>'1', 
    '30'=>'1', '31'=>'1', '32'=>'1', '33'=>'1', '34'=>'1', '35'=>'1', '36'=>'1', '37'=>'1',
    '38'=>'1', '39'=>'1', '40'=>'1', '41'=>'1', '42'=>'1', '43'=>'1',
);
foreach ($scale_key as $k => $v) {
    $config['dictionaries']['corporation']['scale'][$k] = $industry_scale[$v];
}
$config['dictionaries']['focused_feelings'] = array(
    '1'=>'薪资', '2'=>'职位高低', '3'=>'工作职责', '4'=>'公司知名度', 
    '5'=>'公司经营情况', '6'=>'汇报对象', '7'=>'培训/学习', '8'=>'福利', 
    '9' =>'企业文化','10'=>'团队关系',
);

$config['dictionaries']['management_experience']  = array(
        'U'=>'', 'Y'=>'有', 'N'=>'无',''=>'',
        );
$config['dictionaries']['is_add_v']  = array(
         'Y'=>'加V人选', 'N'=>'不加V人选',
        );






if ( defined('ENVIRONMENT') && file_exists( APPPATH . 'config/' . ENVIRONMENT . '/common.config.php' ) ) {
	require_once(APPPATH . 'config/' . ENVIRONMENT . '/common.config.php');
}

/* End of file config.php */
/* Location: ./application/config/config.php */
